version: "3.9"

services:
  postgres:
    image: postgres:16.3
    ports:
      - 5432:5432
    volumes:
      - ~/db-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=listiamo
