# Generated by Django 4.2.11 on 2024-04-30 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='Item',
        ),
    ]
