# Generated by Django 4.2.11 on 2024-04-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_rename_movie_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='link',
            field=models.CharField(blank=True, null=True),
        ),
    ]
