# Generated by Django 4.2.11 on 2024-04-30 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_alter_item_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='listmodel',
            name='last_visited',
            field=models.DateField(default=datetime.date(2024, 4, 30)),
            preserve_default=False,
        ),
    ]
